import type { Metadata } from "next";
import "./globals.css";

// fix this for later to be my personal portfolio
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="antialiased font-[MFDFont]">
        {children}
        </body>
        </html>
    );
}
